### PR TITLE
Added possibility to render TextAnnotation from TextAnnotationModelable for undo / redo -> https://trello.com/c/LsXL3KEk

### PR DESCRIPTION
**Pull request by ulian-onua**

### CODE REVIEW

**Comment by mirkokiefer** [comment]
@ulian-onua could we get the build to pass? Looks like there is an issue with `use of undeclared type 'TextAnnotationModelable'`.

**Comment by ulian-onua** [comment]
> @ulian-onua could we get the build to pass? Looks like there is an issue with `use of undeclared type 'TextAnnotationModelable'`.

@mirkokiefer I didn't use Travis before. Do I need you to grant me any permissions to use it?

**Comment by mirkokiefer** [comment]
@ulian-onua you shouldn't need any permissions since its open-source - just use the link in the PR that is failing:
https://travis-ci.org/blackbeltlabs/TextAnnotation/builds/579445621?utm_source=github_status&utm_medium=notification

Travis just tries to build and (if existing) test the app according to the scripts defined here:
https://github.com/blackbeltlabs/TextAnnotation/blob/master/.travis.yml

**Comment by ulian-onua** [comment]
> @ulian-onua you shouldn't need any permissions since its open-source - just use the link in the PR that is failing:
> https://travis-ci.org/blackbeltlabs/TextAnnotation/builds/579445621?utm_source=github_status&utm_medium=notification
> 
> Travis just tries to build and (if existing) test the app according to the scripts defined here:
> https://github.com/blackbeltlabs/TextAnnotation/blob/master/.travis.yml

Ok. Thanks.

**Comment by ulian-onua** [comment]
@mirkokiefer Travis successfully passed!

**Pull request merged**
